parameters:
  bluesteel42.settings.yml.path: "%kernel.cache_dir%/../data/bluesteel42_settings%"
  bluesteel42.settings.xml.path: "%kernel.cache_dir%/../data/bluesteel42_settings%"
  bluesteel42.settings.doctrinedbal.connection: "default"
  bluesteel42.settings.doctrinedbal.table: "bluesteel42_settings"
  bluesteel42.settings.exceptions: false

services:

  bluesteel42.settings:
    class: BlueSteel42\SettingsBundle\Service\Settings
    arguments:
      - "@bluesteel42.settings.adapter_yml"
      - "%bluesteel42.settings.exceptions%"

  bluesteel42.settings.adapter_doctrinedbal:
    class: BlueSteel42\SettingsBundle\Adapter\DoctrineAdapter
    arguments:
      - "@doctrine"
      - "%bluesteel42.settings.doctrinedbal.connection%"
      - "%bluesteel42.settings.doctrinedbal.table%"
    public: false

  bluesteel42.settings.adapter_yml:
    class: BlueSteel42\SettingsBundle\Adapter\YmlAdapter
    arguments:
      - "@file_locator"
      - "%bluesteel42.settings.yml.path%"
    public: false

  bluesteel42.settings.adapter_xml:
    class: BlueSteel42\SettingsBundle\Adapter\XmlAdapter
    arguments:
      - "@file_locator"
      - "%bluesteel42.settings.xml.path%"
    public: false